loomx.loom_version="1.16-SNAPSHOT"


mod.id = "planets"
mod.name = "Planets"
mod.group = "com.elduin"
mod.version = "2.0"
mod.channel_tag = ""
mod.description = "Space, with real planets. Build a rocket, fly up, and land on the Moon and Mars."
mod.authors = ["Elduin"]
mod.contributors = []
mod.inception_year = "2026"
mod.license.name = "MIT"
mod.license.url = "https://opensource.org/licenses/MIT"
mod.license.dist = "repo"
mod.sources_url = "https://github.com/Elduin-Labs/planets-mod"
mod.homepage_url = "https://github.com/Elduin-Labs/planets-mod"
mod.issues_url = "https://github.com/Elduin-Labs/planets-mod/issues"
mod.discord_url = ""
mod.environment = "client_and_server"
[[mod.pom.developers]]
id = "elduin"
name = "Elduin"
url = "https://github.com/ghost"

[fabric]
deps.fabric-loader = "0.19.5"

[fabric."1.21.4"]
deps.minecraft = "1.21.4"
deps.fabric-api = "0.119.4+1.21.4"
deps.modmenu = "13.0.4"

[fabric."1.21.1"]
deps.minecraft = "1.21.1"
deps.fabric-api = "0.116.17+1.21.1"
deps.modmenu = "11.0.4"
